kelda/kelda

minion/main.go, minion/pprofile/pprofile.go
There is currently only a placeholder method to invoking the profiler,
which is to compile the minion to run with the profiler.
=> minion: Add golang profiler support to the minion

Contributing.md, README.md
This patch adds new documentation on the process for contributing to
quilt, including the coding style and patch submission process.
=> doc: Describe policies around contributing to Quilt

cluster/provider/azure_test.go
Add mutex to avoid race condition in concurrent map writes.
=> azure: Add mutex to azure mock

cluster/provider/cloud_config.go
This patch adds "#!/bin/sh" to the swarm shortcut so that it can
be recognized as a valid script by Go's os/exec.
=> cloud_config: Add bash header to swarm script

cluster/provider/azure.go
We weren't properly returning an error when attempting to load the Azure
credentials. This caused `cluster` to think that the Azure provider was usable,
when it really wasn't.
=> azure: Properly return errors when setting up the Azure provider

Godeps/Godeps.json
The grpc upgrade patch successfully compiled, but a created a
Godep conflict that prevented `godep restore` from working
properly.
=> Godep: Fix conflicting grpc on godep restore

quilt-tester/tester_test.go
The Dockerhub build was failing because `bash` wasn't in the path.
My guess is that this will fix the Dockerhub build. Not 100% sure though.
=> quilt-tester: Change CmdExec test to use `sh`

quilt-tester/exec.go
We were seeing intermittent test failures where not all of the stdout
and stderr output was gathered before returning. This was because
"wait will close the pipe after seeing the command exit". Thus, `Wait()`
would sometimes close the output pipes before the functions grabbing the
output had a chance to read the entire buffer.
=> quilt-tester: Gather command output before `Wait`ing

Makefile, quilt-tester/Dockerfile, quilt-tester/Dockerfile.Dev
Before, the `quilt-tester` and test suite binaries were compiled outside
the Dockerfile environment, and then COPYed in. This wasn't compatible
with the way Dockerhub builds images. This patch makes the
`quilt-tester` Dockerfile self-dependent, and moves the old Dockerfile
to Dockerfile.dev as a convenience for `quilt-tester` developers.
=> quilt-tester: Allow building on Dockerhub

minion/ovsdb/ovsdb.go, minion/ovsdb/ovsdb_mock.go, minion/ovsdb/ovsdb_test.go
Before this patch, ofport was never correctly listed and no flows were
correctly installed. This patch fixes this by parsing the ofport type
correctly.
=> ovsdb: Fix broken network

Dockerfile, quilt-tester/io.go
After this patch, quilt-tester includes in each testing directory
a file called buildinfo. buildinfo contains the commit summary of
the latest commit when the quilt/quilt image was built, and the
GitHub URL for that commit.
=> tester: Provide build information in logs

stitch/key.go, stitch/key_test.go, stitch/stitch_test.go
This patch should solve the github api key rate error problem as you can curl their site for the keys seemingly without limit.
=> stitch: Get github sshkeys with get request instead of github api

quiltctl/ssh/native.go
Before, output/input from the ssh connection were being copied using
threads in io.Copy. Output from connection became truncated in 'quilt
logs' as quilt terminated without checking if the threads had finished
sending and receiving data. To fix, simply set the output/input of the
connection to be stdin/stdout of os which avoids threads altogether.
=> quiltctl: Fix output redirection for 'quilt logs'

quiltctl/command/error.go
Before, when a user tried to run a spec before starting the daemon,
they would only get an error message reporting that they were unable
to connect to the daemon. Now, they will also receive a reminder to
start the daemon before attempting to run a spec.
=> quiltctl: Remind user to start daemon before running spec

.travis.yml, Makefile, scripts/build-push.sh
By building the production Dockerfile as part of CI, we'll catch
errors before they get into the docker build system.  This would have
caught a rather annoying error much earlier in the development
process.
=> travis: Build the production Dockerfile

cluster/provider/cloud_config.go, docs/GettingStarted.md, minion/supervisor/supervisor.go, minion/supervisor/supervisor_test.go, specs/spark/README.md
This patch completely removes docker swarm from the cluster.  Swarm
became obsolete in quilt when the custom scheduler was merged.
Furthermore, it presented somewhat of a security risk as it allowed
remote access to docker containers.
=> minion: Remove docker swarm from the cluster

specs/spark/README.md
The Spark README.md suggested that we run `quilt exec -it` when `quilt
exec` alone is correct.
=> spark: Fix incorrect instruction in README.md

Dockerfile, Dockerfile.Dev, minion/docker/docker.go, minion/docker/docker_test.go, minion/network/worker.go, minion/supervisor/supervisor.go, minion/supervisor/supervisor_test.go
We're currently dealing with a docker bug in which the docker daemon
deadlocks occasionally.  While looking through stack traces we've
noticed that the docker daemon appears to be processing exec calls.
Additionally, a month or two ago we noticed that the minion was making
an exec call at the time of the deadlock.  This patch deals with the
issue by removing all exec calls from the minion.
A happy side effect of the approach this patch takes, is slightly
cleaner code.  All of the exec calls before this patch were to access
OVS utilities that are now bundled with the minion container directly.
=> docker: Stop using docker exec

db/container.go, db/db_test.go, quiltctl/command/command_test.go, quiltctl/command/container.go
The output of `quilt containers` was pretty darn hard to parse before this patch.
=> Pretty print `quilt containers`

quiltctl/command/command_test.go, quiltctl/command/stop.go
'quilt stop' with no arguments will now halt the current cluster.
Consequently, the default namespace for 'quilt stop' is no longer
'default-namespace', so halting 'default-namespace' must now be done
with 'quilt stop default-namespace'.
=> quiltctl: 'quilt stop' halts current cluster

quilt-tester/exec.go, quilt-tester/tester_test.go, util/util.go, util/util_test.go
This generalizes the `waitFor()` function from quilt-tester/exec
to accept an arbitrary timeout and migrates it to the `util` package
so that other packages can make use of it.
=> util: Refactor quilt-tester to use util.WaitFor

minion/etcd/network_test.go
We were getting the following warning in minion/etcd/network_test.go:
`ineffectual assignment to etcdDBCs`.
=> etcd: Fix a compiler warning

README.md
This patch changes ‘ to ', to prevent errors from people that copy
and paste commands from the README.
=> docs: Correct quotation marks

minion/scheduler/worker.go, minion/scheduler/worker_test.go
A recent patch changed it so that IP addresses are allocated by the
master, instead of allocated by docker as they previously were.  As a
result, the join must use the IP address to ensure that the database
container matched with the docker container that received that IP.
=> scheduler: Account for IP in the container join

cluster/cluster.go, cluster/cluster_test.go
The machine join can be rather fuzzy -- multiple database machines may
match a particular cloud machine to varying degrees of fit.  Before
this patch, in some cases it was possible for the join to make poor
(but barely legal) match that preempted a perfect match that could
have been made later.  This patch resolves the issue by doing
the machine join in two stages.  First, it attempts to pair those
machines that match perfectly, before falling back to a fuzzier match
for the leftovers.
=> cluster: Implement a two stage machine join

api/util/util.go, api/util/util_test.go, quiltctl/command/container.go
The new longer stitch IDs required me to copy and paste them from my terminal which I found intolerable.  This series change is it so you need only type the prefix of an ID (much like is possible with git and docker).  It also prints shortened IDs instead of the full length version to make `quilt ps` more readable.
=> Container ID UX Improvements

minion/engine.go, minion/engine_test.go, util/util.go, util/util_test.go
Now that the StitchID is more carefully crafted by Quilt.js, it seems
logical (and makes the system easier to reason about) if a given
container always maintains the same StitchID even as the spec changes.
This fixes a bug where booting a second copy of a particular system
on the same infrastructure could cause new nodes to connect to the
old system.
=> minion: Join containers based exclusively on the StitchID

minion/scheduler/master.go, minion/scheduler/master_test.go
Even when a placement constraint isn't explicitly specified, it would
still be nice to spread out containers with the same image.  While
solving this problem fully doesn't make sense until we've implemented
a more robust scheduler, this patch implements a simple hack that in
practices spreads out similar containers in most cases.
=> scheduler: Try to spread out similar containers

quiltctl/command/run_test.go, stitch/stitch.go
This commit omits empty fields from the Stitch JSON representation for
those fields that can reasonably be empty.  This cleans up the `quilt
run` diff significantly.
=> stitch: Omit empty fields from JSON representation

quiltctl/ssh/native.go, quiltctl/ssh/native_test.go
Previously, using `quilt ssh` or `quilt logs` with an encrypted private
key would show the error `asn1: structure error: length too large`,
which made the actual issue unclear. We now tell the user that
encrypted keys are unsupported and recommend they add the key to
`ssh-agent`.
=> quiltctl: Show a reasonable error on trying to use an encrypted key

minion/supervisor/master.go, minion/supervisor/master_test.go
A previous patch did not run the registry container on Masters, causing
the Mean integration test and the build dockerfile test to fail.
This patch corrects the minion behavior to run the registry properly.
=> supervisor: Fix registry container on Master

quiltctl/command/ssh.go
`quilt ssh` can fail with a tty error if a pty is not allocated for commands that need one.
Unfortunately, there is no good way to catch this command. Printing out the error returned from the native SSH client gives `Process exited with status 1` (lol)
So, this just adds a small help message in `quilt ssh -h` for users to be able to read.
=> quiltctl: Add help message for ssh commands that need to allocate pty

ovs/Dockerfile
Digital Ocean has upgraded to the latest 4.4 kernel, so our OVS
container needs to be updated to reflect that.
=> ovs: Support Linux Kernel 4.4.0-66-generic

.gitignore, .travis.yml, Makefile, api/common.go, api/common_windows.go, minion/run.go, quiltctl/command/minion.go, quiltctl/quiltctl.go, quiltctl/quiltctl_posix.go, quiltctl/ssh/native.go, quiltctl/ssh/resize.go, quiltctl/ssh/resize_windows.go
We hope to allow quilt to be used from windows desktops.  In service
of that goal, this patch supports cross-compiling the binary for
windows.  The resulting binary hasn't been tested, and may not work.
=> build: Build windows executable

stitch/README.md, stitch/stitch.go, stitch/stitch_test.go
This patch adds a new builtin function, readDir(), which allows users
to list the contents of a directory.  With this primitive, users can
slurp up entire trees for inclusion in a container.
Co-Authored-By: Ethan J. Jackson <ejj@eecs.berkeley.edu>
=> stitch: Add readDir() builtin for listing contents of a directory

.travis.yml
By convention docker containers have a "latest" (i.e. default) build
that needs to be updated by the build system.
=> travis: Push master branch as latest tag on docker hub

Makefile
The upcoming release will publish binaries for windows, mac and linux.
This patch makes sure build targets are implemented for all three.
=> build: Add explicit targets for multiple platforms

cluster/cloudcfg/cloudcfg.go, cluster/cloudcfg/cloudcfg_test.go
Previous patches assumed we would tag our containers with a v followed
by the version number.  For example `quilt/quilt:v1.2.3` would be
version 1.2.3 of the quilt container on docker hub.
Unfortunately, git really hates it when branches and tags have the
same version number.  Since this v1.2.3 syntax is standard for tags,
and the docker hub build is generated from the branch name, this patch
drops the v from the docker hub tag number.  This allows us to name
our branches 1.2.3 and our tags v1.2.3 thus avoiding the git
confusion.
=> cluster: Remove "v" from docker hub tag versions

docs/Dev.md
When developing the minion, our current rule in the Makefile does not tag the built minion as "master". When developers write minion code and use the rules in the Makefile to create their own minion image, the deployed minions will try to pull an image tagged with "master" which won't exist. This patch instructs developers to change the version to "latest" for local development so that their personal minions will try to pull the "latest" tag of their build image.
=> docs: Add versioning information to minion section

minion/supervisor/worker.go
A previous patch inserted an ineffectual assignment in worker.go to
keep track of the previous PrivateIP for the worker minion. This value
is not used in running the worker minion, so the assignment was removed.
=> supervisor: Remove ineffectual assignment in worker

docs/GettingStarted.md
Commit 796336a6 (docs: Remove Stitch documentation for Lisp) removed
Stitch.md because it was falling severely out of date.  This caused a
link in GettingStarted.md to be broken.  This patch solves the issue
by removing the offending link.
=> docs: Remove broken link to Stitch.md

CHANGELOG.md, README.md
When the website was recently update, the contact information moved to
the main page.  This patch fixes the relevant links.
=> docs: Fix contact link

quiltctl/command/debug.go, quiltctl/command/debug_test.go, quiltctl/command/log.go, quiltctl/command/log_test.go, quiltctl/command/ps.go, quiltctl/command/ps_test.go, quiltctl/command/run.go, quiltctl/command/run_test.go, quiltctl/command/ssh.go, quiltctl/command/ssh_test.go, quiltctl/command/stop.go, quiltctl/command/version.go, quiltctl/command/version_test.go
This patch causes connectionHelper to be embedded directly into the
various structs that need it, instead of embedding a pointer.  This
slightly simplifies the code.
=> command: Embed connectionHelper directly

.codecov.yaml
We were covering both etcd_mock.go and quilt-tester, neither of which
users interact with, and thus should be excluded.
=> codecov: Tweak ignore directive

minion/network/openflow/openflow.go, minion/network/openflow/openflow_test.go
The OpenFlow tables were needlessly complicated due to a slightly too
clever usage of registers.  This simplifies it without changing the
functionality in any notable way.  This patch also lays the groundwork
for a future patch in which the OpenFlow tables are augmented to
enforce public ACLs.
The first version of this patch (commit e10f2df48) had an error that
caused it to break all network communication and was reverted.  This
version fixed the error.
=> openflow: Refactor and simplify the OpenFlow tables (Attempt 2)

minion/network/openflow/openflow.go, minion/network/openflow/openflow_test.go, minion/network/plugin/plugin.go, minion/scheduler/worker.go, minion/scheduler/worker_test.go
Before this patch, if a container attempted to send packets to the
public internet without permission to.  That packet would leave the
container, traverse our OVS bridge, traverse the NAT unchanged, and be
dumped out onto the public internet with the containers internal
private source IP address.  This is obviously very bad.
This patch solves the issue by enforcing public internet ACLs in the
OpenFlow tables.  Thus, if a container attempts to send a packet to
public that's not allowed, it will be dropped before it leaves the
Quilt OVS bridge.
=> openflow: Enforce ACLs for traffic to and from public

minion/scheduler/worker.go
The minion currently does not support port ranges for public internet,
and logs a warning to aid in debugging.  Unfortunately, that warning
was incorrectly being logged for port ranges over *internal* traffic.
This patch suppresses the warning in that case.
=> scheduler: Avoid spurious warning on port ranges

CHANGELOG.md, quilt.go, quiltctl/command/show.go, quiltctl/command/show_test.go, quiltctl/quiltctl.go
Most people don't know what `ps` is, making the `quilt ps` command
seem jargony and inaccessible.  `show` is much more descriptive and
should be the default.  That said, `ps` is used in other tools, and
some users may expect it to work.  So this patch allows either to be
used.
=> ctl: Rename `ps` to `show` while keeping `ps` as an alias

docs/Makefile
Before, the Makefile would create `build` and `source` directories instead of
copying the contents of those directories into the /site/ directory for the
docs container.
=> docs: Makefile should copy content, not directories

Makefile
Because the `go-coverage` target depends the PACKAGES variable, make
was calling govendor whether or not that target was eventually
evaluated.  The govendor tool may not be installed when a user first
runs `make go-get`, so this would cause spurious warnings.  This patch
pulls the calculation of targets into the body of `go-coverage`,
causing it only to be evaluated when needed.
Reported-By: Diman Todorov <diman.todorov@gmail.com>
=> make: Don't run `govendor` when creating coverage targets

quilt-tester/tests/30-mean/mean.js, quilt-tester/tests/haproxy/haproxy.js, quilt-tester/tests/haproxy/haproxy_test.go
This commit adds an integration test for the updated HAProxy blueprint. It should not be merged until the [updated HAProxy blueprint](https://github.com/quilt/haproxy/pull/6) has been merged.
=> tests: Add integration test for HAProxy

ovs/Dockerfile
Boots on digital ocean are really slow because they upgraded their
kernel.  This patch updates to the latest version.
=> ovs: Update to the latest digital ocean kernel version

quiltctl/command/init/initializer.js
By adding this comment at the top of initializer.js, it can be run
directly without needing to call type node.
=> init: Tell bash initializer.js is a node source file

cloud/google/google.go, db/machine_test.go, minion/network/openflow/openflow.go, minion/pprofile/pprofile.go
The go linter updated with a new rule that checks for unnecessary
checks of error return values.  This patch updates the code to make
the linter happy.
=> lint: Avoid redundant error checks

cloud/cloud.go, cloud/cloud_test.go
In a half hearted attempt to allow inter-region connectivity, we had
set up ACLs allowing explicit communication with every machine.  These
ACLs are unnecessary if every machine is in the same region (which is
the only configuration that Quilt supports at the moment).
Furthermore, they slightly complicated the code, and they had scaling
issues (due to a limit on the maximum number of ACLs supported by the
cloud providers).  This patch removes the functionality.
=> cloud: No longer set up acls between each machine pair

api/client/client.go, cli/command/show.go, cloud/digitalocean/digitalocean.go
The query function had a rather large amount of boilerplate that
wasn't particularly necessary.
=> Reduce cyclomatic complexity (to appease goreportcard.com).

cloud/cloud.go, cloud/status.go
Before this patch, the machine booting status was set outside of the
main join transaction.  This was not technically safe as the namespace
could have changed before that second transaction which could corrupt
the database.   Furthermore, the code was unnecessarily complicated,
and won't work with some upcoming cloud package changes.
=> cloud: Set "Booting" status in the main join() transaction

cloud/foreman/foreman.go
At scale (64 nodes) the foreman can take longer than 10 seconds to
reach all of it's minions.  There are some underlying inefficiencies
here that could be improved, but for now increasing the timeout seems
to help.
=> foreman: Increase minion connection timeouts

api/server/server.go, api/server/server_test.go, cli/command/show.go, cli/command/show_test.go
This reverts commit 60e155a4ad27554f327bd3db90c56a18be23368b.
It's just not quite ready for prime-time yet practically speaking.
=> Revert "api: Query cluster information from cache"

cloud/join.go
Before this patch, the cloud code would write a booting machine to the
database with a role, and then immediately unset that role in the next
run loop.  Not only is this a bit awkward, it causes problems in some
future patches.
=> cloud: Don't assign the role on booting machines

cloud/cloud.go, cloud/google/client/client.go, cloud/google/client/client_test.go, cloud/google/client/mocks/Client.go, cloud/google/google.go, cloud/google/google_test.go, vendor/google.golang.org/api/compute/v1/compute-api.json, vendor/google.golang.org/api/compute/v1/compute-gen.go, vendor/google.golang.org/api/gensupport/send.go, vendor/vendor.json
This patch rewrites most of the Google network related code in service of
several goals.  First, it creates a Google network per region rather than
requiring all regions to share a single network.  This facilitates us,
second, cleaning up the Google network in regions that are unused.  Third,
it generally simplifies the ACL code such that it's more readable, less
redundant, and easier to test.  And finally, it adds unit tests for the
sections of the code that it updates.
=> google: Refactor the network architecture

cloud/digitalocean/client/client.go, cloud/digitalocean/client/client_test.go, cloud/digitalocean/client/mocks/Client.go, cloud/digitalocean/digitalocean.go, cloud/digitalocean/digitalocean_test.go
Digital Ocean has a rather aggressive API request limit that we're
hitting in integration tests.  Part of the problem, is that the API is
global, serving all regions, rather than segregated per region as it
is in other cloud providers.  This means that instead of making a
single List() call that could request all droplets, we were making a
list call per region, artificially inflating our requests per second.
This patch solves the issue by caching the result of a List() call for
1 second, allowing it to be reused by other regions without making API
requests.
=> digitalocean: Cache List() calls

cloud/join.go, cloud/join_test.go
Before this patch, the cloud preferred to join machines with known
roles even if that meant reassigning a floating IP away from a machine
with an unknown role to a different worker with a known role.  This
meant that on boot (or namespace change), a perfectly health machine
could have its floating IP taken away from it, simply because one of
its peers declared its role to the daemon before it got a chance to.
There's really no particular reason for this preference, so this patch
fixes the issue by reversing it.  All things being equal, we will
prefer to match a machine with the correct floating IP, even if that
means its role is unknown.
=> cloud: Prefer to leave a floating IP in place when possible
