quilt-tester/bin/quilt-tester
stitch/get.go

😦 
(@ejj the Docker container for quilt-tester will have to be rebuilt)

Fix quilt get and quilt-tester

---

minion/network/network.go
minion/network/network_test.go
minion/ovsdb/ovsdb.go
minion/ovsdb/ovsdb_test.go

Change ports to have the same name as their IP and rework network.go:runMaster to use a hashjoin

Minion network

---

cluster/cluster.go
cluster/provider/amazonReserved.go
cluster/provider/amazonSpot.go
cluster/provider/wait.go
cluster/provider/wait_test.go

More Amazon fixes

---

README.md
docs/readme_test.go

This patch syntax highlights the JavaScript code snippets in the
README.

readme: Syntax highlight code snippets

---

minion/ovsdb/ovsdb_mock.go

Simplifies things a bit, main reason is the report card though.

ovsdb: Break up ovsdb mock apply method

---

specs/haproxy/scripts/start.go

For whatever reason, DNS resolution was not reliable. Instead of trying
to solve it, we're switching the wait method.

haproxy: Change from resolving DNS to ping

---

quilt-tester/tests/30-mean/check_mean.go

Hopefully this will help us debug failures a little bit more easily.

tests: Log containers in the mean test

---

quiltctl/command/run.go
quiltctl/command/run_test.go
vendor/github.com/fatih/color/LICENSE.md
vendor/github.com/fatih/color/README.md
vendor/github.com/fatih/color/color.go
vendor/github.com/fatih/color/doc.go
vendor/github.com/mattn/go-colorable/LICENSE
vendor/github.com/mattn/go-colorable/README.md
vendor/github.com/mattn/go-colorable/colorable_others.go
vendor/github.com/mattn/go-colorable/colorable_windows.go
vendor/github.com/mattn/go-colorable/noncolorable.go
vendor/github.com/mattn/go-isatty/LICENSE
vendor/github.com/mattn/go-isatty/README.md
vendor/github.com/mattn/go-isatty/doc.go
vendor/github.com/mattn/go-isatty/isatty_appengine.go
vendor/github.com/mattn/go-isatty/isatty_bsd.go
vendor/github.com/mattn/go-isatty/isatty_linux.go
vendor/github.com/mattn/go-isatty/isatty_solaris.go
vendor/github.com/mattn/go-isatty/isatty_windows.go
vendor/vendor.json

Uses github.com/fatih/color to colorize diff output printed to the console.

quiltctl: Colored diff output

---

minion/network/worker.go
minion/network/worker_test.go
minion/supervisor/supervisor.go
minion/supervisor/supervisor_test.go
vendor/github.com/vishvananda/netlink/link.go
vendor/github.com/vishvananda/netlink/link_linux.go
vendor/github.com/vishvananda/netlink/netlink_unspecified.go
vendor/github.com/vishvananda/netlink/nl/link_linux.go
vendor/github.com/vishvananda/netlink/qdisc_linux.go
vendor/vendor.json

This is a real PR, please actually review it.

Finishing up the migration to the netlink library

---

api/client/client_test.go
api/server/server_test.go
db/container.go
db/label.go
minion/etcd/minion.go
minion/etcd/minion_test.go
minion/etcd/network.go
minion/etcd/network_test.go
minion/etcd/run.go
minion/network/network.go
minion/network/network_test.go
minion/network/worker.go
minion/scheduler/worker.go
quilt-tester/tests/10-network/check_network.go

Most of these are small fixes in preparation for moving IP allocation to the master.

Various network Tweaks

---

specs/haproxy/scripts/start.go

The way we currently configure HAProxy, it resolves the hostnames of
its backend servers once at startup.  If that DNS resolution times out
because OVS is not yet configured, HAProxy will crash.  The correct
long term solution to this problem is to configure HAProxy to resolve
host names at runtime as necessary.  However, until that's
implemented, this patch resurrects old DNS resolution code that was
pulled out originally because it didn't play nicely with /etc/hosts,
but should now work.
This should fix the broken quilt-tester.

haproxy: Reimplement dns resolution at startup

---

specs/django/Dockerfile
specs/django/django-example.js
specs/django/django.js
specs/spec_test.go

A basic Django specification running with Gunicorn and MongoDB.

specs: Implement a Django specification

---

quilt-tester/tests/30-mean/check_mean.go

Adds new test to POST data to the quilt/mean-service, and then ensures that this
data is available.
Basically all this test does is just post 10x from each public IP, and then checks on each public IP if all the data is available. Not super great since I think the haproxy instances can all just route to the same instance or something, but we can always increase the amount of times we post/get.

ci: Test POSTed data in mean test

---

cluster/cluster.go
cluster/cluster_test.go

Before, it was possible for `machine.Machine`s to flip-flop between `db.Machine`s
in the cluster join. The join has been updated to now break ties between machines
by prioritizing joining machines that have the same PublicIP and other attributes.
Additionally, assigning FloatingIPs was updated. FloatingIPs are now only assigned
once the CloudID of a machine has been assigned. This ensures that FloatingIPs will
only be assigned once the machine has fully booted and been stabilized in the join
(meaning, it will not join with any other machine).
Tests have been corrected and added to reflect these changes.
==============================================================
Seemed fine locally with the logs test, but I haven't really been able to test this with floating IP outside of unit tests, …

cluster: Fix join shuffling and FloatingIP discrepancies

---

cluster/amazon/amazon.go
cluster/amazon/amazon_test.go

Before, we would include pending reserved machines in `List`. This
resulted in a bug where the cluster would prematurely try to update
floating IPs on instances that had not yet fully booted.
We now block machine boot and stops until they are no longer pending.
If we time out before machines transition to the "running" state, we
destroy them to avoid leaking machines that might not ever properly
transition.

amazon: Don't include pending instances in `List`

---

cluster/cluster.go

In addition to setting  up all of the providers for all of the regions
when the Quilt daemon is started, this commit additionally attempts to
setup a provider when it's needed by a spec.  This makes error
handling easier, and also means that Quilt will attempt to fix setup
errors by re-connecting to the provider in every iteration of the loop
(whereas currently, if Quilt fails to connect to a provider, it will
never re-try).
Co-Authored-By: Ethan J. Jackson <ejj@eecs.berkeley.edu>

cluster: Set up providers on demand

---

minion/supervisor/worker.go
ovs/Dockerfile

Upgrade OVS to 2.7 and make `ovn-controller` not restart every time
Both commits were tested using quilt-tester locally once, all tests passed

Ovs upgrade

---

README.md
docs/_BlueprintAPI.md
docs/_BlueprintWritersGuide.md
docs/_CloudProviders.md
docs/_GettingStarted.md
docs/_QuiltCLI.md

Eventually, we should automatically check that docs are linted, just like we test that the README compiles.

Lint and tweak docs

---

cloud/cloud.go
cloud/cloud_test.go
cloud/misc_test.go

It's not adding a lot of value over db.Machine.

cloud: Get rid of the joinMachine struct

---

cloud/credentials.go
db/logger.go
minion/vault/api.go

These things came up as I was hacking on scale.  More to come.

Various small tweaks.

---

cloud/google/google.go

Google doesn't appear to support booting instances in batches, and
doing so one at a time takes too long for large numbers of instances.
This patch parallelizes the process, which seems to speed up booting
significantly, and stopping a little bit.

google: Parallelize boot and stop

---

cloud/amazon/amazon.go
cloud/amazon/amazon_test.go
cloud/amazon/client/client.go
cloud/amazon/client/client_test.go
cloud/amazon/client/mocks/Client.go
cloud/cloud.go
cloud/cloud_test.go
cloud/digitalocean/client/client.go
cloud/digitalocean/client/client_test.go
cloud/digitalocean/client/mocks/Client.go
cloud/digitalocean/digitalocean.go
cloud/digitalocean/digitalocean_test.go
cloud/google/google.go
cloud/vagrant/vagrant.go
kelda.go

Most of these are aimed at scaling to 64 nodes for spark.

Various digital ocean tweaks.
